### PR TITLE
🐛 Fix handling multiple repos

### LINKED ISSUE #1: Can't handle Multiple repos
Current Behavior:
- If the workspace contains multiple repos, The branch name of the first repo will be taken into account.

Expected Behaviour: 
- The extension should understand from where it is triggered and select repos accordingly.

### PR DESCRIPTION
**Pull request by xenomech**
Added repo filtering based on the trigger.

### CODE REVIEW

File: src/extension.js [hunk 1]
```diff
@@ -8,8 +8,9 @@ function activate(context) {
 	const { defaultExpression, errors, successMsg, gitURL, genericInfoMsg } = require("./constants/common")
 	vscode.window.showInformationMessage(successMsg.activeMsg);
 
-	let disposable = vscode.commands.registerCommand('prefixed.prefixTicketID', async function () {
+	let disposable = vscode.commands.registerCommand('prefixed.prefixTicketID', async function (trigger) {
 		try {
+			console.log(trigger)
```
Comment (xenomech) [inline src/extension.js]: .
